graphql:
  servlet:
    playground:
      enable: true
spring:
  datasource:
    url: jdbc:h2:~/companydb
    DB_CLOSE_DELAY: -1
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false